variable aws_region {}
variable environment_name {}
variable vpc_id {}
variable instance_type {}
variable subnet_id {}
variable key_name {}
variable chef_server_address {}
variable ec2_pem {}
variable chef_pem {}
